In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv(r"C:\Users\s8908\Churn_Modelling.csv")

In [3]:
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
x=dataset.iloc[:,3:13]#1st column - include all
#2nd column - which columns
y=dataset.iloc[:,13]

In [5]:
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [6]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [7]:
#create dummy variable
Geography = pd.get_dummies(x['Geography'],drop_first = True)
Gender    = pd.get_dummies(x['Gender'],drop_first=True)

In [8]:
Gender,Geography

(      Male
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 9995     1
 9996     1
 9997     0
 9998     1
 9999     0

 [10000 rows x 1 columns],
       Germany  Spain
 0           0      0
 1           0      1
 2           0      0
 3           0      0
 4           0      1
 ...       ...    ...
 9995        0      0
 9996        0      0
 9997        0      0
 9998        1      0
 9999        0      0

 [10000 rows x 2 columns])

In [9]:
x=x.drop(['Geography','Gender'], axis=1)

In [10]:
x=pd.concat([x,Gender,Geography], axis=1)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [12]:
#FEATURE SCALING
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -1.09168714,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.30102557, -1.37744033, ...,  0.91601335,
         1.75486502, -0.57369368],
       [-1.19119591, -0.94312892, -1.031415  , ..., -1.09168714,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ...,  0.91601335,
        -0.5698444 , -0.57369368],
       [-0.62420521, -0.08179119,  1.39076231, ..., -1.09168714,
        -0.5698444 ,  1.74309049],
       [-0.28401079,  0.87525072, -1.37744033, ..., -1.09168714,
         1.75486502, -0.57369368]])

In [14]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ..., -1.09168714,
         1.75486502, -0.57369368],
       [-1.31490297,  0.10961719, -1.031415  , ..., -1.09168714,
        -0.5698444 , -0.57369368],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -1.09168714,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ...,  0.91601335,
        -0.5698444 ,  1.74309049],
       [-0.00566991, -0.46460796, -0.33936434, ...,  0.91601335,
         1.75486502, -0.57369368],
       [-0.79945688, -0.84742473,  1.04473698, ...,  0.91601335,
         1.75486502, -0.57369368]])

In [16]:
import keras
from tensorflow.keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [25]:
#Initalizing ANN 
classifier = Sequential()
#Adding first input layer and first hidden layer 
classifier.add(Dense(units=6, kernel_initializer='he_uniform', activation='relu', input_dim=11))

In [26]:
#Adding 2nd hidden layer
classifier.add(Dense(units=10, kernel_initializer='he_uniform', activation='relu'))

In [27]:
#Adding output layer
classifier.add(Dense(units=1, kernel_initializer='glorot_uniform', activation='sigmoid'))

In [28]:
#compiling Ann model
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [29]:
#Fitting ANN to training set 
model_history = classifier.fit(X_train, y_train, validation_split=0.33, batch_size=10, epochs=100)

Epoch 1/100
536/536 [==============================] - 4s 4ms/step - loss: 0.5456 - accuracy: 0.7511 - val_loss: 0.4757 - val_accuracy: 0.7955
Epoch 2/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4584 - accuracy: 0.7964 - val_loss: 0.4536 - val_accuracy: 0.7993
Epoch 3/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4392 - accuracy: 0.8000 - val_loss: 0.4423 - val_accuracy: 0.8027
Epoch 4/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4295 - accuracy: 0.8080 - val_loss: 0.4361 - val_accuracy: 0.8050
Epoch 5/100
536/536 [==============================] - 2s 5ms/step - loss: 0.4231 - accuracy: 0.8140 - val_loss: 0.4302 - val_accuracy: 0.8103
Epoch 6/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4175 - accuracy: 0.8188 - val_loss: 0.4266 - val_accuracy: 0.8137
Epoch 7/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4125 - accuracy: 0.8233 - val_loss: 0.4222 - val_accuracy: 0.8209
Epoch 8/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4067 - accuracy: 0.8298 - val_loss: 0.4175 - val_accuracy: 0.8224
Epoch 9/100
536/536 [==============================] - 2s 5ms/step - loss: 0.4024 - accuracy: 0.8322 - val_loss: 0.4153 - val_accuracy: 0.8224
Epoch 10/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3984 - accuracy: 0.8341 - val_loss: 0.4084 - val_accuracy: 0.8307
Epoch 11/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3943 - accuracy: 0.8377 - val_loss: 0.4036 - val_accuracy: 0.8330
Epoch 12/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3897 - accuracy: 0.8395 - val_loss: 0.3995 - val_accuracy: 0.8330
Epoch 13/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3855 - accuracy: 0.8395 - val_loss: 0.3960 - val_accuracy: 0.8326
Epoch 14/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3799 - accuracy: 0.8410 - val_loss: 0.3894 - val_accuracy: 0.8391
Epoch 15/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3756 - accuracy: 0.8447 - val_loss: 0.3869 - val_accuracy: 0.8402
Epoch 16/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3715 - accuracy: 0.8444 - val_loss: 0.3844 - val_accuracy: 0.8379
Epoch 17/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3671 - accuracy: 0.8455 - val_loss: 0.3809 - val_accuracy: 0.8368
Epoch 18/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3629 - accuracy: 0.8461 - val_loss: 0.3783 - val_accuracy: 0.8379
Epoch 19/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3591 - accuracy: 0.8496 - val_loss: 0.3759 - val_accuracy: 0.8413
Epoch 20/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3566 - accuracy: 0.8530 - val_loss: 0.3736 - val_accuracy: 0.8413
Epoch 21/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3534 - accuracy: 0.8539 - val_loss: 0.3724 - val_accuracy: 0.8444
Epoch 22/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3503 - accuracy: 0.8565 - val_loss: 0.3722 - val_accuracy: 0.8440
Epoch 23/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3496 - accuracy: 0.8546 - val_loss: 0.3703 - val_accuracy: 0.8432
Epoch 24/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3473 - accuracy: 0.8567 - val_loss: 0.3713 - val_accuracy: 0.8417
Epoch 25/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3464 - accuracy: 0.8556 - val_loss: 0.3707 - val_accuracy: 0.8448
Epoch 26/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3436 - accuracy: 0.8582 - val_loss: 0.3712 - val_accuracy: 0.8455
Epoch 27/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3440 - accuracy: 0.8584 - val_loss: 0.3687 - val_accuracy: 0.8451
Epoch 28/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3427 - accuracy: 0.8589 - val_loss: 0.3695 - val_accuracy: 0.8451
Epoch 29/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3415 - accuracy: 0.8584 - val_loss: 0.3677 - val_accuracy: 0.8459
Epoch 30/100
536/536 [==============================] - 2s 5ms/step - loss: 0.3403 - accuracy: 0.8586 - val_loss: 0.3679 - val_accuracy: 0.8448
Epoch 31/100
536/536 [==============================] - 3s 6ms/step - loss: 0.3409 - accuracy: 0.8614 - val_loss: 0.3684 - val_accuracy: 0.8448
Epoch 32/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3396 - accuracy: 0.8582 - val_loss: 0.3704 - val_accuracy: 0.8444
Epoch 33/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3396 - accuracy: 0.8591 - val_loss: 0.3684 - val_accuracy: 0.8448
Epoch 34/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3389 - accuracy: 0.8595 - val_loss: 0.3692 - val_accuracy: 0.8474
Epoch 35/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3392 - accuracy: 0.8567 - val_loss: 0.3693 - val_accuracy: 0.8455
Epoch 36/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3386 - accuracy: 0.8576 - val_loss: 0.3674 - val_accuracy: 0.8466
Epoch 37/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3375 - accuracy: 0.8556 - val_loss: 0.3680 - val_accuracy: 0.8470
Epoch 38/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3381 - accuracy: 0.8584 - val_loss: 0.3698 - val_accuracy: 0.8448
Epoch 39/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3374 - accuracy: 0.8595 - val_loss: 0.3687 - val_accuracy: 0.8470
Epoch 40/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3370 - accuracy: 0.8587 - val_loss: 0.3689 - val_accuracy: 0.8474
Epoch 41/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3363 - accuracy: 0.8586 - val_loss: 0.3706 - val_accuracy: 0.8436
Epoch 42/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3370 - accuracy: 0.8584 - val_loss: 0.3693 - val_accuracy: 0.8448
Epoch 43/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3353 - accuracy: 0.8584 - val_loss: 0.3665 - val_accuracy: 0.8482
Epoch 44/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3361 - accuracy: 0.8593 - val_loss: 0.3689 - val_accuracy: 0.8474
Epoch 45/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3358 - accuracy: 0.8610 - val_loss: 0.3659 - val_accuracy: 0.8531
Epoch 46/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3350 - accuracy: 0.8612 - val_loss: 0.3663 - val_accuracy: 0.8463
Epoch 47/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3347 - accuracy: 0.8604 - val_loss: 0.3656 - val_accuracy: 0.8463
Epoch 48/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3349 - accuracy: 0.8602 - val_loss: 0.3650 - val_accuracy: 0.8485
Epoch 49/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3344 - accuracy: 0.8614 - val_loss: 0.3661 - val_accuracy: 0.8501
Epoch 50/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3334 - accuracy: 0.8578 - val_loss: 0.3659 - val_accuracy: 0.8523
Epoch 51/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3332 - accuracy: 0.8619 - val_loss: 0.3647 - val_accuracy: 0.8531
Epoch 52/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3326 - accuracy: 0.8582 - val_loss: 0.3629 - val_accuracy: 0.8519
Epoch 53/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3325 - accuracy: 0.8582 - val_loss: 0.3643 - val_accuracy: 0.8482
Epoch 54/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3328 - accuracy: 0.8612 - val_loss: 0.3643 - val_accuracy: 0.8474
Epoch 55/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3321 - accuracy: 0.8604 - val_loss: 0.3634 - val_accuracy: 0.8512
Epoch 56/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3324 - accuracy: 0.8610 - val_loss: 0.3627 - val_accuracy: 0.8504
Epoch 57/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3319 - accuracy: 0.8621 - val_loss: 0.3647 - val_accuracy: 0.8512

Epoch 58/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3307 - accuracy: 0.8612 - val_loss: 0.3649 - val_accuracy: 0.8485
Epoch 59/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3315 - accuracy: 0.8589 - val_loss: 0.3635 - val_accuracy: 0.8501
Epoch 60/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3299 - accuracy: 0.8612 - val_loss: 0.3678 - val_accuracy: 0.8512
Epoch 61/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3308 - accuracy: 0.8589 - val_loss: 0.3626 - val_accuracy: 0.8550
Epoch 62/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3302 - accuracy: 0.8630 - val_loss: 0.3635 - val_accuracy: 0.8504
Epoch 63/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3292 - accuracy: 0.8642 - val_loss: 0.3665 - val_accuracy: 0.8482
Epoch 64/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3302 - accuracy: 0.8621 - val_loss: 0.3635 - val_accuracy: 0.8482
Epoch 65/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3294 - accuracy: 0.8610 - val_loss: 0.3659 - val_accuracy: 0.8463
Epoch 66/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3294 - accuracy: 0.8587 - val_loss: 0.3624 - val_accuracy: 0.8523
Epoch 67/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3282 - accuracy: 0.8621 - val_loss: 0.3624 - val_accuracy: 0.8512
Epoch 68/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3297 - accuracy: 0.8615 - val_loss: 0.3633 - val_accuracy: 0.8501
Epoch 69/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3286 - accuracy: 0.8628 - val_loss: 0.3633 - val_accuracy: 0.8554
Epoch 70/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3287 - accuracy: 0.8619 - val_loss: 0.3621 - val_accuracy: 0.8554
Epoch 71/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3284 - accuracy: 0.8636 - val_loss: 0.3614 - val_accuracy: 0.8504
Epoch 72/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3292 - accuracy: 0.8621 - val_loss: 0.3628 - val_accuracy: 0.8523
Epoch 73/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3284 - accuracy: 0.8621 - val_loss: 0.3613 - val_accuracy: 0.8561
Epoch 74/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3285 - accuracy: 0.8612 - val_loss: 0.3631 - val_accuracy: 0.8501
Epoch 75/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3285 - accuracy: 0.8625 - val_loss: 0.3608 - val_accuracy: 0.8489
Epoch 76/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3287 - accuracy: 0.8634 - val_loss: 0.3613 - val_accuracy: 0.8527
Epoch 77/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3279 - accuracy: 0.8630 - val_loss: 0.3626 - val_accuracy: 0.8501
Epoch 78/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3283 - accuracy: 0.8615 - val_loss: 0.3647 - val_accuracy: 0.8516
Epoch 79/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3282 - accuracy: 0.8621 - val_loss: 0.3616 - val_accuracy: 0.8508
Epoch 80/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3274 - accuracy: 0.8636 - val_loss: 0.3614 - val_accuracy: 0.8516
Epoch 81/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3280 - accuracy: 0.8615 - val_loss: 0.3646 - val_accuracy: 0.8523
Epoch 82/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3280 - accuracy: 0.8606 - val_loss: 0.3628 - val_accuracy: 0.8535
Epoch 83/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3273 - accuracy: 0.8632 - val_loss: 0.3658 - val_accuracy: 0.8565
Epoch 84/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3273 - accuracy: 0.8617 - val_loss: 0.3601 - val_accuracy: 0.8512
Epoch 85/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3270 - accuracy: 0.8653 - val_loss: 0.3632 - val_accuracy: 0.8512
Epoch 86/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3271 - accuracy: 0.8615 - val_loss: 0.3617 - val_accuracy: 0.8470
Epoch 87/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3278 - accuracy: 0.8630 - val_loss: 0.3615 - val_accuracy: 0.8523
Epoch 88/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3265 - accuracy: 0.8628 - val_loss: 0.3670 - val_accuracy: 0.8538
Epoch 89/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3276 - accuracy: 0.8636 - val_loss: 0.3620 - val_accuracy: 0.8550
Epoch 90/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3269 - accuracy: 0.8628 - val_loss: 0.3616 - val_accuracy: 0.8497
Epoch 91/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3275 - accuracy: 0.8630 - val_loss: 0.3606 - val_accuracy: 0.8527
Epoch 92/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3271 - accuracy: 0.8630 - val_loss: 0.3608 - val_accuracy: 0.8573
Epoch 93/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3265 - accuracy: 0.8619 - val_loss: 0.3623 - val_accuracy: 0.8519
Epoch 94/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3266 - accuracy: 0.8619 - val_loss: 0.3645 - val_accuracy: 0.8519
Epoch 95/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3268 - accuracy: 0.8643 - val_loss: 0.3638 - val_accuracy: 0.8485
Epoch 96/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3272 - accuracy: 0.8604 - val_loss: 0.3613 - val_accuracy: 0.8485
Epoch 97/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3260 - accuracy: 0.8628 - val_loss: 0.3603 - val_accuracy: 0.8546
Epoch 98/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3270 - accuracy: 0.8623 - val_loss: 0.3601 - val_accuracy: 0.8497
Epoch 99/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3262 - accuracy: 0.8634 - val_loss: 0.3606 - val_accuracy: 0.8527
Epoch 100/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3267 - accuracy: 0.8638 - val_loss: 0.3594 - val_accuracy: 0.8501

In [30]:
print(model_history.history.keys())

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [31]:
#On testing data
y_pred = classifier.predict(X_test)

63/63 [==============================] - 0s 2ms/step

In [37]:
y_pred

array([[0.30139104],
       [0.32974005],
       [0.08972281],
       ...,
       [0.08413059],
       [0.1813943 ],
       [0.24787746]], dtype=float32)

In [38]:
import numpy as np

# Assuming you have the predicted probabilities in the 'predictions' variable
predicted_probabilities = y_pred

# Convert probabilities to binary predictions
threshold = 0.5
predicted_classes = (predicted_probabilities >= threshold).astype(int)

print(predicted_classes)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]

In [39]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predicted_classes)
#calculate accuracy
from sklearn.metrics import accuracy_score
score = accuracy_score(predicted_classes,y_test)

In [44]:
print(cm,"confusion matrix")

[[1511   84]
 [ 191  214]] confusion matrix

In [45]:
print(score,"accuracy on train data")

0.8625 accuracy on train data